### ISSUE TITLE
OOP-1-review-2022-10-15

### ISSUE THREAD

**Issue by hamerlinski** [Gladziu/oop-put-course#1]
**Task 1**
- [ ] Proper communication/interaction between classes and objects is missing.
- [x] Rename repository to **oop-put-course**
- [x] Store all code in one repository

**Task 2**
- [x] Class doesn't have cohesion. Each constructor create completely different object 👎
